//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoursWork
    {
        public int EmployeeId { get; set; }
        public Nullable<int> TimeIn { get; set; }
        public Nullable<int> TimeOut { get; set; }
        public Nullable<int> HoursWork1 { get; set; }
        public Nullable<int> HourlyRate { get; set; }
        public Nullable<int> GrossPay { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
