//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRoll
    {
        public int EmployeeId { get; set; }
        public Nullable<int> TotalWorkHours { get; set; }
        public Nullable<int> HourlyRate { get; set; }
        public Nullable<int> Deductions { get; set; }
        public Nullable<int> NetPay { get; set; }
        public string Month { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCompiled { get; set; }
    }
}
