//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int EmployeeId { get; set; }
        public string Title { get; set; }
        public string JobLevel { get; set; }
        public string SkillCategory { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
