//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int EmployeeId { get; set; }
        public string TotalWorkHours { get; set; }
        public string Totalvacation { get; set; }
        public string TotalBreak { get; set; }
        public string TotalLeave { get; set; }
        public string HourlyRate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
